name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v5
      - name: Check
        run: |
          uv run ruff check
          uv run ruff format --check
          uv run mypy
      - name: Test
        run: uv run pytest
