name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v5
      - uses: astral-sh/ruff-action@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
      - name: Mypy
        run: uv run mypy --group dev
      - name: Test
        run: uv run pytest --group dev
      - name: Build docs
        run: uv run mkdocs build --group docs
